# Generated by Django 5.2.1 on 2025-06-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shareidea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=150)),
                ('email_address', models.EmailField(max_length=254)),
                ('idea', models.CharField(max_length=254)),
                ('descri_ption', models.TextField()),
            ],
        ),
    ]
