# Generated by Django 5.2.1 on 2025-06-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareidea',
            old_name='user',
            new_name='username',
        ),
    ]
